import {
  ProcurementTask,
  User,
  Farmer,
  HarvestTask,
} from "@/types";

/* ─── Mock Users ─────────────────────────────────────────────── */
export const mockUsers: User[] = [
  {
    id: "u1",
    name: "Rajesh Kumar",
    email: "rajesh@startrek.com",
    role: "MAIN_ADMIN",
    isActive: true,
    createdAt: new Date("2026-01-01"),
  },
  {
    id: "u2",
    name: "Priya Menon",
    email: "priya@startrek.com",
    role: "OFFICE_ADMIN",
    isActive: true,
    createdAt: new Date("2026-01-05"),
  },
  {
    id: "s1",
    name: "Arjun Nair",
    email: "arjun@startrek.com",
    role: "SUPERVISOR",
    isActive: true,
    createdAt: new Date("2026-02-01"),
  },
  {
    id: "s2",
    name: "Suresh Pillai",
    email: "suresh@startrek.com",
    role: "SUPERVISOR",
    isActive: true,
    createdAt: new Date("2026-02-10"),
  },
  {
    id: "s3",
    name: "Deepak Raj",
    email: "deepak@startrek.com",
    role: "SUPERVISOR",
    isActive: true,
    createdAt: new Date("2026-03-01"),
  },
];

/* ─── Mock Farmers ───────────────────────────────────────────── */
export const mockFarmers: Farmer[] = [
  {
    id: "f1",
    name: "Murugan Selvam",
    mobileNumber: "9876543210",
    address: "Thovalai, Kanyakumari District, Tamil Nadu",
    createdAt: new Date("2026-05-10"),
  },
  {
    id: "f2",
    name: "Rajan Krishnan",
    mobileNumber: "9865432109",
    address: "Agastheeswaram, Kanyakumari District, Tamil Nadu",
    createdAt: new Date("2026-06-01"),
  },
  {
    id: "f3",
    name: "Chandran Pillai",
    mobileNumber: "9754321098",
    address: "Marthandam, Kanyakumari District, Tamil Nadu",
    createdAt: new Date("2026-06-15"),
  },
  {
    id: "f4",
    name: "Govindasamy",
    mobileNumber: "9643210987",
    address: "Colachel, Kanyakumari District, Tamil Nadu",
    createdAt: new Date("2026-07-01"),
  },
  {
    id: "f5",
    name: "Balan Pillai",
    mobileNumber: "9532109876",
    address: "Nagercoil, Kanyakumari District, Tamil Nadu",
    createdAt: new Date("2026-07-10"),
  },
];

/* ─── Mock Procurement Tasks ─────────────────────────────────── */
export const mockTasks: ProcurementTask[] = [
  {
    id: "t1",
    farmerId: "f1",
    farmer: mockFarmers[0],
    approxTonnage: 12,
    status: "APPROVED_PROCUREMENT",
    supervisorId: "s1",
    supervisor: mockUsers[2],
    assignedAt: new Date("2026-07-20T09:00:00"),
    actualTonnage: 11.4,
    ratioPercentage: 78,
    quality: "GOOD",
    rate: 2200,
    supervisorSubmittedAt: new Date("2026-07-21T14:30:00"),
    particulars: [
      { id: "p1", taskId: "t1", boxType: "13KG" },
      { id: "p2", taskId: "t1", boxType: "16KG" },
    ],
    finalRate: 2200,
    approvedById: "u2",
    approvedBy: mockUsers[1],
    approvedAt: new Date("2026-07-22T10:00:00"),
    createdAt: new Date("2026-07-19T11:00:00"),
  },
  {
    id: "t2",
    farmerId: "f2",
    farmer: mockFarmers[1],
    approxTonnage: 8,
    status: "FIELD_SUBMITTED",
    supervisorId: "s2",
    supervisor: mockUsers[3],
    assignedAt: new Date("2026-07-25T09:00:00"),
    actualTonnage: 7.2,
    ratioPercentage: 82,
    quality: "EXCELLENT",
    supervisorSubmittedAt: new Date("2026-07-26T16:00:00"),
    particulars: [
      { id: "p3", taskId: "t2", boxType: "13KG" },
      { id: "p4", taskId: "t2", boxType: "13_5KG" },
    ],
    createdAt: new Date("2026-07-24T10:00:00"),
  },
  {
    id: "t3",
    farmerId: "f3",
    farmer: mockFarmers[2],
    approxTonnage: 15,
    status: "ASSIGNED",
    supervisorId: "s1",
    supervisor: mockUsers[2],
    assignedAt: new Date("2026-07-28T10:00:00"),
    createdAt: new Date("2026-07-27T14:00:00"),
  },
  {
    id: "t4",
    farmerId: "f4",
    farmer: mockFarmers[3],
    approxTonnage: 6,
    status: "PENDING_ASSIGNMENT",
    createdAt: new Date("2026-07-29T09:00:00"),
  },
];

/* ─── Mock Harvesting Tasks (Module 2) ────────────────────────── */
export const mockHarvestTasks: HarvestTask[] = [
  {
    id: "ht1",
    procurementTaskId: "t1",
    farmerName: "Murugan Selvam",
    mobileNumber: "9876543210",
    address: "Thovalai, Kanyakumari District",
    tonnage: 11.4,
    quality: "GOOD",
    finalRate: 2200,
    status: "READY_FOR_HARVEST",
    createdAt: new Date("2026-07-22T10:05:00"),
  },
  {
    id: "ht2",
    procurementTaskId: "t102",
    farmerName: "Velusamy Pillai",
    mobileNumber: "9812345678",
    address: "Padmanabhapuram, Kanyakumari",
    tonnage: 14.2,
    quality: "EXCELLENT",
    finalRate: 2350,
    status: "HARVEST_ASSIGNED",
    teamName: "Harvest Team 3 (Thovalai)",
    brandName: "StarPremium Export Grade",
    chemicals: ["ETHYLENE_WASH", "FUNGICIDE_DIP"],
    pingIntervalHours: 2,
    assignedAt: new Date("2026-07-28T08:00:00"),
    createdAt: new Date("2026-07-27T11:00:00"),
  },
  {
    id: "ht3",
    procurementTaskId: "t103",
    farmerName: "Karthik Raja",
    mobileNumber: "9712345678",
    address: "Radhapuram, Kanyakumari",
    tonnage: 9.8,
    quality: "GOOD",
    finalRate: 2150,
    status: "HARVEST_IN_PROGRESS",
    teamName: "Harvest Team 1 (North Kanyakumari)",
    brandName: "GreenGold Fresh",
    chemicals: ["ALUM_TREATMENT", "PROTECTIVE_COATING"],
    pingIntervalHours: 2,
    harvestedBoxes: 420,
    assignedAt: new Date("2026-07-29T07:00:00"),
    startedAt: new Date("2026-07-29T09:30:00"),
    createdAt: new Date("2026-07-28T10:00:00"),
  },
  {
    id: "ht4",
    procurementTaskId: "t104",
    farmerName: "Subramanian",
    mobileNumber: "9612345678",
    address: "Nagercoil, Kanyakumari",
    tonnage: 16.5,
    quality: "EXCELLENT",
    finalRate: 2400,
    status: "DISPATCHED_TO_COLD_STORAGE",
    teamName: "Harvest Team 6 (Nagercoil)",
    brandName: "StarPremium Export Grade",
    chemicals: ["ETHYLENE_WASH", "FUNGICIDE_DIP", "PROTECTIVE_COATING"],
    pingIntervalHours: 2,
    harvestedBoxes: 680,
    truckNumber: "TN-74-AX-8921",
    driverName: "Shanmugam",
    driverPhone: "9412345678",
    assignedAt: new Date("2026-07-26T08:00:00"),
    startedAt: new Date("2026-07-26T10:00:00"),
    completedAt: new Date("2026-07-26T16:00:00"),
    dispatchedAt: new Date("2026-07-26T17:30:00"),
    createdAt: new Date("2026-07-25T09:00:00"),
  },
];

/* ─── Logged-in User (mock session) ──────────────────────────── */
export const mockCurrentUser = {
  admin: mockUsers[0],      // MAIN_ADMIN
  office: mockUsers[1],     // OFFICE_ADMIN
  supervisor: mockUsers[2], // SUPERVISOR (Arjun)
};
